package cn.dtmusic.api.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_categories.category_id
     *
     * @mbg.generated Sat Oct 10 15:58:54 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_categories.category_name
     *
     * @mbg.generated Sat Oct 10 15:58:54 CST 2020
     */
    private String categoryName;

    private String categoryTypeName;

    public String getCategoryTypeName() {
        return categoryTypeName;
    }

    public void setCategoryTypeName(String categoryTypeName) {
        this.categoryTypeName = categoryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_categories.category_id
     *
     * @return the value of t_categories.category_id
     *
     * @mbg.generated Sat Oct 10 15:58:54 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_categories.category_id
     *
     * @param categoryId the value for t_categories.category_id
     *
     * @mbg.generated Sat Oct 10 15:58:54 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_categories.category_name
     *
     * @return the value of t_categories.category_name
     *
     * @mbg.generated Sat Oct 10 15:58:54 CST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_categories.category_name
     *
     * @param categoryName the value for t_categories.category_name
     *
     * @mbg.generated Sat Oct 10 15:58:54 CST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }
}
