package cn.dtmusic.api.entity;

import java.util.List;

import cn.dtmusic.api.dto.AlbumDto;
import cn.dtmusic.api.dto.SongDto;

public class Singer {
    private Integer singerId;

    private Byte resourceType;

    private String singerName;

    private String singerNickname;

    private String singerImg;

    private String singerType;

    private String singerLanguage;

    private String singerDescription;

    private Integer collectionCount;

    private Byte singerStatus;

    private SongDto song;

    private AlbumDto album;

    private Integer songCount;

    private Integer albumCount;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Integer getSongCount() {
        return songCount;
    }

    public void setSongCount(Integer songCount) {
        this.songCount = songCount;
    }

    public Integer getAlbumCount() {
        return albumCount;
    }

    public void setAlbumCount(Integer albumCount) {
        this.albumCount = albumCount;
    }

    public SongDto getSong() {
        return song;
    }

    public void setSong(SongDto song) {
        this.song = song;
    }

    public AlbumDto getAlbum() {
        return album;
    }

    public void setAlbum(AlbumDto album) {
        this.album = album;
    }

    private List<SongDto> songs;

    private List<AlbumDto> albums;

    public List<SongDto> getSongs() {
        return songs;
    }

    public void setSongs(List<SongDto> songs) {
        this.songs = songs;
    }

    public List<AlbumDto> getAlbums() {
        return albums;
    }

    public void setAlbums(List<AlbumDto> albums) {
        this.albums = albums;
    }

    public Integer getSingerId() {
        return singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.singer_id
     *
     * @param singerId the value for t_singer.singer_id
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setSingerId(Integer singerId) {
        this.singerId = singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_singer.singer_name
     *
     * @return the value of t_singer.singer_name
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public String getSingerName() {
        return singerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.singer_name
     *
     * @param singerName the value for t_singer.singer_name
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setSingerName(String singerName) {
        this.singerName = singerName == null ? null : singerName.trim();
    }

    public String getSingerNickname() {
        return singerNickname;
    }

    public void setSingerNickname(String singerNickname) {
        this.singerNickname = singerNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_singer.singer_img
     *
     * @return the value of t_singer.singer_img
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */


    public String getSingerImg() {
        return singerImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.singer_img
     *
     * @param singerImg the value for t_singer.singer_img
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setSingerImg(String singerImg) {
        this.singerImg = singerImg == null ? null : singerImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_singer.singer_type
     *
     * @return the value of t_singer.singer_type
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public String getSingerType() {
        return singerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.singer_type
     *
     * @param singerType the value for t_singer.singer_type
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setSingerType(String singerType) {
        this.singerType = singerType == null ? null : singerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_singer.singer_language
     *
     * @return the value of t_singer.singer_language
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public String getSingerLanguage() {
        return singerLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.singer_language
     *
     * @param singerLanguage the value for t_singer.singer_language
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setSingerLanguage(String singerLanguage) {
        this.singerLanguage = singerLanguage == null ? null : singerLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_singer.singer_description
     *
     * @return the value of t_singer.singer_description
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public String getSingerDescription() {
        return singerDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.singer_description
     *
     * @param singerDescription the value for t_singer.singer_description
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setSingerDescription(String singerDescription) {
        this.singerDescription = singerDescription == null ? null : singerDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_singer.collection_count
     *
     * @return the value of t_singer.collection_count
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public Integer getCollectionCount() {
        return collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.collection_count
     *
     * @param collectionCount the value for t_singer.collection_count
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setCollectionCount(Integer collectionCount) {
        this.collectionCount = collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_singer.singer_status
     *
     * @return the value of t_singer.singer_status
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public Byte getSingerStatus() {
        return singerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_singer.singer_status
     *
     * @param singerStatus the value for t_singer.singer_status
     *
     * @mbg.generated Sun Sep 27 20:20:53 CST 2020
     */
    public void setSingerStatus(Byte singerStatus) {
        this.singerStatus = singerStatus;
    }

    public Byte getResourceType() {
        return resourceType;
    }

    public void setResourceType(Byte resourceType) {
        this.resourceType = resourceType;
    }
}
